### ISSUE TITLE
payload too large - nothing but 40 lines of es6 w/ async, xml2js, and axios

### ISSUE THREAD

**Issue by robbiemu** [auth0/wt-cli#110]
I'm reporting this as it was requested at the bottom of the log there. :)

source:
```js
'use latest'
'use strict'

require("babel-polyfill");

import {get} from 'axios'
import {parseString} from 'xml2js'

const deviantArtAPI = 'http://backend.deviantart.com/rss.xml'

function getRandomIntInclusive(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function xml2jsPromise(data) {
  return new Promise((resolve, reject) => {
    parseString(data, 
      (err, result) => err? reject(err) : resolve(result))
  })
}

/* here be magic */
export default async (context, callback) => {
  // surprisingly, there's no raw queryString on context.
  const paramstring = Object.entries(context.data)
    .reduce((p,c) => { 
      const key = encodeURIComponent(c[0])
      const val = encodeURIComponent(c[1])
      p.push(key + '=' + val)
      return p 
    }, []).join('&') || 'order=67108864&offset=0&q=overwatch'

console.log('requesting: ' + deviantArtAPI + '?' + paramstring)

    // getting the RSS feed of images requested, either from a search configured 
    // from the provided query string, or from the default
    let rawRSS
    try {
      rawRSS = await get(deviantArtAPI + '?' + paramstring)
        .catch(e => {throw e})
      console.log('...done')
    } catch (e) {
      console.error(e)
    }

    let oRes //object of Result
    try {
      oRes = await xml2jsPromise(rawRSS.data)
    } catch(e) {
      console.error(e)
    }

    let images = []
    oRes.rss.channel[0].item
      .forEach(i => {
        images.push(i['media:content'][0]['$'].url)
      })
    
    const imageURL = images[getRandomIntInclusive(0, images.length - 1)]

console.log('requesting image: ' + imageURL)

     return await get(imageURL)
}
```
with babelrc
```
{ 
  "presets": ["es2015"],
  "plugins": ["add-module-exports","syntax-async-functions","transform-regenerator"]
  }
```

producing:
```
PS C:\Users\roberto\github\auth0-webtask> wt create --bundle ./deviantart.js
onWebtaskError Error: Payload Too Large
    at Request.callback (C:\Users\roberto\AppData\Roaming\npm\node_modules\wt-cli\node_modules\superagent\lib\node\index
.js:698:17)
    at IncomingMessage.<anonymous> (C:\Users\roberto\AppData\Roaming\npm\node_modules\wt-cli\node_modules\superagent\lib
\node\index.js:922:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Uncaught error:  Request body size exceeds 122880
Error: Payload Too Large
    at Request.callback (C:\Users\roberto\AppData\Roaming\npm\node_modules\wt-cli\node_modules\superagent\lib\node\index
.js:698:17)
    at IncomingMessage.<anonymous> (C:\Users\roberto\AppData\Roaming\npm\node_modules\wt-cli\node_modules\superagent\lib
\node\index.js:922:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Please report this at: https://github.com/auth0/wt-cli/issues
```

**Comment by robbiemu** [comment]
ps> on my end, when I run this code I get output like:
```
PS C:\Users\roberto\github\auth0-webtask> npm run build; npm test

> autho0-webtask@1.0.0 build C:\Users\roberto\github\auth0-webtask
> babel deviantart.js -o dist/deviantart.js


> autho0-webtask@1.0.0 test C:\Users\roberto\github\auth0-webtask
> node test.js

Promise { <pending> }
requesting: http://backend.deviantart.com/rss.xml?order=67108864&offset=0&q=overwatch
...done
requesting image: http://pre05.deviantart.net/f1ca/th/pre/i/2016/324/5/8/overwatch_s_zarya_by_pixiepowde
g
PS C:\Users\roberto\github\auth0-webtask> npm test

> autho0-webtask@1.0.0 test C:\Users\roberto\github\auth0-webtask
> node test.js

Promise { <pending> }
requesting: http://backend.deviantart.com/rss.xml?order=67108864&offset=0&q=overwatch
...done
requesting image: http://img14.deviantart.net/fdd1/i/2016/206/e/0/overwatch_d_va_by_aoandou-da6nk8a.jpg
```

**Comment by ggoodman** [comment]
@robbiemu can you give this a try once again with `v6.0.0`?

**Comment by NotMyself** [comment]
Hi @robbiemu,

Were you able to resolve this issue? It looks like @ggoodman asked you to try with version 6.0.0 of the CLI. We are currently on version 9.5.0. I am going to close this issue. If you are still experiencing the issue feel free to reopen it with current details.

Thanks!
