### ISSUE TITLE
wt update broken

### ISSUE THREAD

**Issue by ivanoats** [auth0/wt-cli#113]
`wt update` was working fine earlier today but now I'm getting this error after installing v5.0.0

```
$ wt update variable-stripe-button variable-pay-button.js
Uncaught error:  Cannot read property 'length' of undefined
<details>
TypeError: Cannot read property 'length' of undefined
    at createWebtask (/Users/ivan/.nvm/versions/node/v7.7.4/lib/node_modules/wt-cli/lib/createWebtask.js:21:26)
    at onClaims (/Users/ivan/.nvm/versions/node/v7.7.4/lib/node_modules/wt-cli/bin/update.js:89:16)
From previous event:
    at Namespace.handleUpdate [as $handler] (/Users/ivan/.nvm/versions/node/v7.7.4/lib/node_modules/wt-cli/bin/update.js:77:10)
    at Array.eval (eval at makeMethodCaller (/Users/ivan/.nvm/versions/node/v7.7.4/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/call_get.js:18:12), <anonymous>:9:36)
    at Array.tryCatcher (/Users/ivan/.nvm/versions/node/v7.7.4/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ivan/.nvm/versions/node/v7.7.4/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/ivan/.nvm/versions/node/v7.7.4/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/ivan/.nvm/versions/node/v7.7.4/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/ivan/.nvm/versions/node/v7.7.4/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/ivan/.nvm/versions/node/v7.7.4/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/ivan/.nvm/versions/node/v7.7.4/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
Please report this at: https://github.com/auth0/wt-cli/issues
</details>
```

**Comment by ivanoats** [comment]
this might be an issue with my setup? getting the same error on v4.0.6

**Comment by nicoecheza** [comment]
having the same issue here

**Comment by ivanoats** [comment]
Confirmed fixed, thanks
