### ISSUE TITLE
`auth0 create` fails with "Cannot read property 'length' of undefined" error

### ISSUE THREAD

**Issue by thameera** [auth0/wt-cli#114]
I'm trying to create a pre-registration hook via CLI and getting the following error:

```
$  auth0 create -t pre-user-registration --name my-extension-1 -p tham-default file.js
Uncaught error:  Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createWebtask (/usr/local/lib/node_modules/wt-cli/lib/createWebtask.js:21:26)
    at _create (/usr/local/lib/node_modules/wt-cli/bin/auth0_create.js:131:16)
    at /usr/local/lib/node_modules/wt-cli/bin/auth0_create.js:110:16
    at tryCatcher (/usr/local/lib/node_modules/wt-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/wt-cli/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/wt-cli/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/wt-cli/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/local/lib/node_modules/wt-cli/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/wt-cli/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/wt-cli/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Please report this at: https://github.com/auth0/wt-cli/issues
```

wt-cli version: `5.1.2`
Also `wt profile ls` shows the `tham-default` profile.

What could have gone wrong?

**Comment by the-s0urce** [comment]
Adding "if(!args.dependencies) args.dependencies='';" to line 21 of "[...]\nodejs\node_modules\wt-cli\lib\createWebtask.js" fixed it for me.
