### ISSUE TITLE
Bundler is not resolving peer dependencies

### ISSUE THREAD

**Issue by rohit-ravikoti** [auth0/wt-cli#127]
When using lokka with lokka-transport-http:

```
Rohits-Air:activation-code-generator-wt rohitravikoti$ wt create index.js --bundle
* Hint: If you would like to opt-out from this behaviour, pass in the --ignore-package-json flag.
Resolving 3 modules...
Provisioning 3 modules...
lokka@1.7.0 is available
lokka-transport-http@1.6.1 is available
voucher-code-generator@1.1.1 is available
Webtask created
​
You can access your webtask at the following url:
​
https://wt-6d6ba479746756b8590f0b6221de0b05-0.run.webtask.io/activation-code-generator
​
Error I get when I follow the URL:
​
{
  "code": 400,
  "message": "Compilation failed: Cannot find module 'lokka/transport'",
  "error": "Cannot find module 'lokka/transport'",
  "stack": "Error: Cannot find module 'lokka/transport'\n    at Function.Module._resolveFilename (module.js:325:15)\n    at Function.Module._load (module.js:276:25)\n    at Module.require (module.js:353:17)\n    at require (internal/module.js:12:17)\n    at Object.<anonymous> (/data/_verquire/lokka-transport-http/1.6.1/node_modules/lokka-transport-http/dist/index.js:40:18)\n    at Module._compile (module.js:409:26)\n    at Object.Module._extensions..js (module.js:416:10)\n    at Module.load (module.js:343:32)\n    at Function.Module._load (module.js:300:12)\n    at Module.require (module.js:353:17)\n    at require (internal/module.js:12:17)"
}
```

**Comment by heymartinadams** [comment]
Same here.

```
wt create http://code.affiliategenius.com/webtask.js --name AffiliateGenius --secret privateKey=__PRIVATE_KEY__ --parse-body --meta 'wt-node-dependencies'='{"affiliategenius-test":"1.0.15"}'
```

As you can see below, from the [`webtask.js`](http://code.affiliategenius.com/webtask.js) file, it requires a simple [npm package](https://www.npmjs.com/package/affiliategenius-test) that’s dynamically loaded via the `--meta` tag:
```
'use latest'
var AffiliateGenius = require('affiliategenius-test@1.0.15')
module.exports = (context, callback) => AffiliateGenius(context, callback)
```

Yet the resulting [webtask](https://wt-607887792589a1d1a518ce2c83b6dddd-0.run.webtask.io/AffiliateGenius) says it’s not available:
```
Compilation failed: Cannot find module 'affiliategenius-test@1.0.15'
```
