### ISSUE TITLE
Uncaught error:  logs.once is not a function when using --raw mode for logs

### ISSUE THREAD

**Issue by AmaanC** [auth0/wt-cli#131]
Node v6.10.2
wt-cli v6.1.0

```
-> % wt logs -r
{ container: 'wt-edd4eda6a3c7d2d18e96f5ca1beea6ad-0' } 'connected to streaming logs'
Uncaught error:  logs.once is not a function
TypeError: logs.once is not a function
    at Bluebird (/home/amaan/.nvm/versions/node/v6.10.2/lib/node_modules/wt-cli/bin/logs.js:48:14)
    at tryCatcher (/home/amaan/.nvm/versions/node/v6.10.2/lib/node_modules/wt-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/home/amaan/.nvm/versions/node/v6.10.2/lib/node_modules/wt-cli/node_modules/bluebird/js/main/promise.js:483:31)
    at new Promise (/home/amaan/.nvm/versions/node/v6.10.2/lib/node_modules/wt-cli/node_modules/bluebird/js/main/promise.js:71:37)
    at Namespace.handleLogs [as $handler] (/home/amaan/.nvm/versions/node/v6.10.2/lib/node_modules/wt-cli/bin/logs.js:40:12)
    at Array.eval (eval at makeMethodCaller (/home/amaan/.nvm/versions/node/v6.10.2/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/call_get.js:18:12), <anonymous>:9:36)
    at Array.tryCatcher (/home/amaan/.nvm/versions/node/v6.10.2/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/amaan/.nvm/versions/node/v6.10.2/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/amaan/.nvm/versions/node/v6.10.2/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/amaan/.nvm/versions/node/v6.10.2/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/home/amaan/.nvm/versions/node/v6.10.2/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/amaan/.nvm/versions/node/v6.10.2/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/amaan/.nvm/versions/node/v6.10.2/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

----

Issue is caused here:
https://github.com/auth0/wt-cli/blob/master/bin/logs.js#L48
https://github.com/auth0/wt-cli/blob/master/lib/logs.js#L17
https://github.com/mrrama/node-bunyan-prettystream/blob/master/lib/prettystream.js#L414

`/bin/logs.js` assumes the returned `logger` from `/lib/logs.js` will be a `PrettyStream` logger, which inherits the `.once` from Node.js' `require('stream').Stream`.

**Comment by arcseldon** [comment]
FYI only. reply from a user with similar issue.

```
npm install wt-cli@5.1.3
npm install webtask-bundle@2.3.0

I anchored the wt-cli to a known good version, issue resolved.
```

**Comment by gene1wood** [comment]
`--raw` continues to not work today in the current version of wt-cli
