### ISSUE TITLE
Uncaught error:  Request body size exceeds 1000

### ISSUE THREAD

**Issue by vishal3011** [auth0/wt-cli#132]
Uncaught error:  Request body size exceeds 1000
Error: Payload Too Large
    at Request.callback (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:675:11)
    at /usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:883:18
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/parsers/json.js:16:7)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

This error shows up! Can anyone help?

**Comment by rwtombaugh** [comment]
This is a legitimate error that you'll receive when the request body is too large. You need to reduce the size of the request body. Are you trying to bundle the webtask with dependencies? That can lead to a large code payload.
