### ISSUE TITLE
`wt init` fails -> TypeError: Cannot read property 'then' of null

### ISSUE THREAD

**Issue by tommy-a** [auth0/wt-cli#170]
When trying to run `wt init tommy2030@gmail.com` for the first time, it fails with the following error

```bash
TypeError: Cannot read property 'then' of null
    at detectAuthMode (/Users/tommy/.nvm/versions/node/v7.10.0/lib/node_modules/wt-cli/bin/profile/init.js:96:9)
    at verifyUserOrReturnProfile (/Users/tommy/.nvm/versions/node/v7.10.0/lib/node_modules/wt-cli/bin/profile/init.js:69:15)
    at tryCatcher (/Users/tommy/.nvm/versions/node/v7.10.0/lib/node_modules/wt-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/tommy/.nvm/versions/node/v7.10.0/lib/node_modules/wt-cli/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/Users/tommy/.nvm/versions/node/v7.10.0/lib/node_modules/wt-cli/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/Users/tommy/.nvm/versions/node/v7.10.0/lib/node_modules/wt-cli/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/Users/tommy/.nvm/versions/node/v7.10.0/lib/node_modules/wt-cli/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/tommy/.nvm/versions/node/v7.10.0/lib/node_modules/wt-cli/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Users/tommy/.nvm/versions/node/v7.10.0/lib/node_modules/wt-cli/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Please report this at: https://github.com/auth0/wt-cli/issues
```

**Comment by NotMyself** [comment]
Confirmed in version 8.1.0

![screen shot 2017-11-10 at 12 13 09 pm](https://user-images.githubusercontent.com/73120/32676770-b400ca02-c610-11e7-86da-89d51f52bc1a.png)

**Comment by NotMyself** [comment]
Resovled in wt-cli@8.1.1
