### ISSUE TITLE
"Payload Too Large" after trying to update a webtask in node8 with bundling

### ISSUE THREAD

**Issue by juan-m12i** [auth0/wt-cli#179]
hi there, I am receiving the following message when trying to upload a webtask with several internal file dependencies and some npm modules. Any hint?
 
Thanks a lot

Best,
J

Resolving 2 modules...
Provisioning 2 modules...
nonce@1.0.4 is available
truelayer-client@1.0.9 is available
onWebtaskError Error: Payload Too Large
    at Request.callback (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:696:15)
    at parser (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:906:18)
    at IncomingMessage.res.on (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/parsers/json.js:19:7)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
Uncaught error:  Request body size exceeds 122880
Error: Payload Too Large
    at Request.callback (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:696:15)
    at parser (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:906:18)
    at IncomingMessage.res.on (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/parsers/json.js:19:7)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
Please report this at: https://github.com/auth0/wt-cli/issues

**Comment by juan-m12i** [comment]
Sorry, went too fast with the recommendation in the console, before checking for previous issues. I am importing a large module I guess
