### ISSUE TITLE
wt profile migrate doesn't work

### ISSUE THREAD

**Issue by Darkhogg** [auth0/wt-cli#198]
I'm performing the exact steps described on [the wiki page](https://github.com/auth0/wt-cli/wiki/Node8) using `wt-cli@9.2.0` but all I get is an error:

```console
$ wt -v        
9.2.0

$ wt profile get    
Profile:     default
URL:         https://webtask.it.auth0.com
Container:   wt-2c726e1c3ef253fa63110f41c9cfef5b-0
Version:     v1
* Hint: Use --show-token to show the token for this profile.

$ wt profile migrate
usage: wt profile [-h] {init,ls,get,rm,nuke} ...
wt profile: error: argument "profile_command": Invalid choice: migrate (choose from [init, ls, get, rm, nuke])
```

Is this not implemented yet or am I doing something wrong??

**Comment by tjanczuk** [comment]
@Darkhogg Please use the wt-cli@9.3.0 (or later) and instructions from https://github.com/auth0/wt-cli/wiki/Node8---wt-cli

**Comment by Darkhogg** [comment]
@tjanczuk I get this error when running `wt profile migrate --finalize`:

```
/usr/lib/node_modules/wt-cli/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

TypeError: w.toJSON is not a function
    at d.forEach.w (/usr/lib/node_modules/wt-cli/lib/node4Migration.js:129:46)
    at Array.forEach (<anonymous>)
    at profile.(anonymous function) (/usr/lib/node_modules/wt-cli/lib/node4Migration.js:129:19)
    at tryCatcher (/usr/lib/node_modules/wt-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (/usr/lib/node_modules/wt-cli/node_modules/bluebird/js/main/nodeify.js:23:30)
    at Promise._settlePromiseAt (/usr/lib/node_modules/wt-cli/node_modules/bluebird/js/main/promise.js:582:21)
    at Promise._settlePromises (/usr/lib/node_modules/wt-cli/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/lib/node_modules/wt-cli/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/lib/node_modules/wt-cli/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/wt-cli/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
```

**Comment by glennblock** [comment]
Hi @DarkHogg

Sorry if it was not clear. You have to first run with —yes (not —finalize).
This will migrate your Webtasks. Then you can verify the tasks that were
migrated work in Node 8. Once you are sure everything migrated properly /
and everything works (you may have need to make some changes) then you can
use —finalize to make it permanent. You should only do this last step once
you are sure because your old tasks will be deleted from the Node 4
deployment.

Glenn

**Comment by glennblock** [comment]
Ok thanks. We will look into it. Glad you were able to use the web UI.

**Comment by tjanczuk** [comment]
@Darkhogg Can you please share your OS, node.js version, and wt-cli version you were using when you encountered the error?

**Comment by Darkhogg** [comment]
Linux (Arch Linux, kernel 4.16.3), Node.js 8.11.1, wt-cli 9.3.0

**Comment by mattiaocchiuto** [comment]
Same problem, I'm trying to migrate my `default` profile by using the `wt profile migrate default --yes` command by I receive the following error in response:
```
Error: Not Found
    at Request.callback (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:706:15)
    at parser (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:916:18)
    at IncomingMessage.res.on (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/parsers/json.js:19:7)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Please report this at: https://github.com/auth0/wt-cli/issues
```

wt version: 9.4.0

**Comment by NotMyself** [comment]
Profile migration has been removed from the CLI.
