### ISSUE TITLE
Cannot find module 'express' when trying to run debug.

### ISSUE THREAD

**Issue by JPGMC** [auth0/wt-cli#207]
When trying to understand why I would randomly get HTTP 500 errors on my Node 8 tasks, I decided to run debug. When 'wt debug' on my javascript, I got the following:

Debugger listening on ws://127.0.0.1:9229/94fedcdf-030b-47bd-8899-df3e4c783c3c
For help see https://nodejs.org/en/docs/inspector

Uncaught error:  Error starting local server: Cannot find module 'express'

Error: Error starting local server: Cannot find module 'express'
    at Bluebird (/usr/local/lib/node_modules/wt-cli/bin/serve.js:86:31)
    at tryCatcher (/usr/local/lib/node_modules/wt-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/usr/local/lib/node_modules/wt-cli/node_modules/bluebird/js/main/promise.js:483:31)
    at new Promise (/usr/local/lib/node_modules/wt-cli/node_modules/bluebird/js/main/promise.js:71:37)
    at createServer (/usr/local/lib/node_modules/wt-cli/bin/serve.js:71:26)
    at Namespace.handleWebtaskServe [as $handler] (/usr/local/lib/node_modules/wt-cli/bin/serve.js:57:27)
    at Array.eval (eval at makeMethodCaller (/usr/local/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/call_get.js:18:12), <anonymous>:9:36)
    at Array.tryCatcher (/usr/local/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/usr/local/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/usr/local/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:757:18)
    at tryOnImmediate (timers.js:718:5)
    at processImmediate [as _immediateCallback] (timers.js:698:5)

Please report this at: https://github.com/auth0/wt-cli/issues

**Comment by NotMyself** [comment]
Hi @JPGMC,

When running locally you need to have your dependencies available as well. Try `npm init --yes` followed by an `npm install express --save`. Then try debugging.

**Comment by JPGMC** [comment]
Thanks, I installed the different dependencies missing and it's not running.
