### ISSUE TITLE
Uncaught error:  Error starting local server: Unexpected token import

### ISSUE THREAD

**Issue by sunnyagarwal008** [auth0/wt-cli#211]
Error: Error starting local server: Unexpected token import
    at Bluebird (/usr/local/lib/node_modules/wt-cli/bin/serve.js:86:31)
    at tryCatcher (/usr/local/lib/node_modules/wt-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/usr/local/lib/node_modules/wt-cli/node_modules/bluebird/js/main/promise.js:483:31)
    at new Promise (/usr/local/lib/node_modules/wt-cli/node_modules/bluebird/js/main/promise.js:71:37)
    at createServer (/usr/local/lib/node_modules/wt-cli/bin/serve.js:71:26)
    at Namespace.handleWebtaskServe [as $handler] (/usr/local/lib/node_modules/wt-cli/bin/serve.js:57:27)
    at Array.eval (eval at makeMethodCaller (/usr/local/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/call_get.js:18:12), <anonymous>:9:36)
    at Array.tryCatcher (/usr/local/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/usr/local/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/usr/local/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/wt-cli/node_modules/structured-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by NotMyself** [comment]
Hello @sunnyagarwal008,

Can you give me a little context on this error? What exactly were you trying to do when you received this error?

**Comment by NotMyself** [comment]
Hi @sunnyagarwal008,

I am going to close this issue for now. If you have a chance to respond feel free to reopen it.
