### ISSUE TITLE
getaddrinfo EAI_AGAIN sandbox.auth0-extend.com:443

### ISSUE THREAD

**Issue by martinhbramwell** [auth0/wt-cli#213]
```
Uncaught error:  getaddrinfo EAI_AGAIN sandbox.auth0-extend.com:443
Error: getaddrinfo EAI_AGAIN sandbox.auth0-extend.com:443
    at Object._errnoException (util.js:1022:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
Please report this at: https://github.com/auth0/wt-cli/issues
npm ERR! code ELIFECYCLE
npm ERR! errno 99
npm ERR! webtasksso@1.0.0 updw: `wt update -p $npm_package_config_profile --watch --bundle $npm_package_name ./src`
npm ERR! Exit status 99
npm ERR! 
npm ERR! Failed at the webtasksso@1.0.0 updw script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/you/.npm/_logs/2018-06-02T20_11_46_142Z-debug.log

```

**Comment by NotMyself** [comment]
Hi @martinhbramwell,

Can you give me a little context for this error? What were you attempting to do when this happened?

**Comment by martinhbramwell** [comment]
That's so long ago, I really can't remember.
I think it was a one off thing, that suddenly popped up while saving changes.

Networking glitch?

**Comment by NotMyself** [comment]
Quite possibly. I am going to close the issue. Let me know if you encounter it again. Thanks!
