### ISSUE TITLE
Error Socket Hangup

### ISSUE THREAD

**Issue by darkyen** [auth0/wt-cli#51]
I tried making a webtask which simply emits things to pusher, [extraneous: notoriously pusher has webpack as an optional dependency]. When I run the command 

``` bash
wt create --no-parse --secret Some=Secret --bundle index.js
```

I get the following error, I assume that it might be caused by the resulting package being too large. 

```
Error: socket hang up
    at createHangUpError (_http_client.js:210:15)
    at TLSSocket.socketOnEnd (_http_client.js:295:23)
    at emitNone (events.js:73:20)
    at TLSSocket.emit (events.js:167:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)
```

**Comment by colllin** [comment]
I'm hitting the same issue.  My package is quite large (>100kb).  Could that be it?

**Comment by rwtombaugh** [comment]
Yes, there is a 100kb limit to the size of the webtask payload. This is by design. However, this does not include npm modules that you require as dependencies.
