### ISSUE TITLE
Uncaught error:  Request body size exceeds 122880

### ISSUE THREAD

**Issue by kevinl95** [auth0/wt-cli#63]
When creating a webtask for a .js file that is 2.6MB I receive the following:
`Uncaught error:  Request body size exceeds 122880
Error: Payload Too Large
    at Request.callback (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:698:17)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:922:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
Please report this at: https://github.com/auth0/wt-cli/issues`
The file was created using Webtask Bundle and was including the GCloud module if it helps to reproduce the problem.

**Comment by kevinl95** [comment]
Support confirmed there is a 100kb filesize limit.
