### ISSUE TITLE
Uncaught error:  Request body size exceeds 122880, Payload Too Large

### ISSUE THREAD

**Issue by timendez** [auth0/wt-cli#65]
I'm trying to create a task with a 1.5MB directory. 

Here's the stacktrace:

```
Uncaught error:  Request body size exceeds 122880
Error: Payload Too Large
    at Request.callback (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:698:17)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:922:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
Please report this at: https://github.com/auth0/wt-cli/issues
child_process.js:507
    throw err;
    ^

Error: Command failed: wt create /Users/REDACTED/Code/REDACTED <REDACTED>
Uncaught error:  Request body size exceeds 122880
Error: Payload Too Large
    at Request.callback (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:698:17)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:922:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
Please report this at: https://github.com/auth0/wt-cli/issues

  at checkExecSyncError (child_process.js:464:13)
  at Object.execSync (child_process.js:504:13)
  at Object.<anonymous> (/Users/<REDACTED>/Code/<REDACTED>.js:41:14)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:968:3
```

**Comment by timendez** [comment]
I was requiring node modules (request, jsonwebtoken) that were already present on webtask. Just needed to remove them.
