### ISSUE TITLE
Problem updating task

### ISSUE THREAD

**Issue by jonberke** [auth0/wt-cli#71]
I just started playing with Webtasks, but when I try to update the sample script, I get an error:

```
$ wt update hello hello.js
Uncaught error:  Invalid query: ValidationError: child "decrypt" fails because ["decrypt" must be a number]
Error: Bad Request
    at Request.callback (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:698:17)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/wt-cli/node_modules/superagent/lib/node/index.js:922:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
Please report this at: https://github.com/auth0/wt-cli/issues
```

**Comment by ggoodman** [comment]
Hello @jonberke, we apologize for this error. This was the result of a deployment to the platform that raised validation to a level beyond reason. We've launched a re-deployment that should come online shortly.

**Comment by NotMyself** [comment]
Hi @jonberke,

I am attempting to clean up our old issues and pull requests. This issue is pretty old and appears to be resolved. I am going to close it. If you are still experiencing issues, please reopen and let me know.
